import type { Config } from "tailwindcss";

const config: Config = {
    mode: "jit",
    darkMode: ["class"],
    content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            backgroundImage: {
                "hero-image": "url(../public/assets/hero-image.png)",
                "why-us-bg-image": "url(../public/assets/why-us-bg-image.png)",
                "sendmo-download-app-bg":
                    "url(../public/assets/sendmo-download-app-bg.png)",
                "sendmo-contact-bg": "url(../public/assets/line-vector4.png)",
                "alpay-advantages-bg": "url(../public/assets/dots-world.png)",
                "alpay-how-it-works-bg": "url(../public/assets/wavy-lines.png)",
            },
            colors: {
                "primary-blue": "#0039BA",
                "secondary-blue": "#0067F8",
                tertiary: "rgba(226, 241, 255, 1)",
                "dark-blue": "#001036",
                "gray-1": "#969696",
                "gray-2": "#ACACAC",
                "orange-1": "#FF5500",
                "green-1": "#20CB70",
                primary: "var(--primary)",
                "primary-deep": "var(--primary-deep)",
                "primary-mild": "var(--primary-mild)",
                "primary-subtle": "var(--primary-subtle)",
                error: "var(--error)",
                "error-subtle": "var(--error-subtle)",
                success: "var(--success)",
                "success-subtle": "var(--success-subtle)",
                info: "var(--info)",
                "info-subtle": "var(--info-subtle)",
                warning: "var(--warning)",
                "warning-subtle": "var(--warning-subtle)",
                neutral: "var(--neutral)",
                "gray-50": "var(--gray-50)",
                "gray-100": "var(--gray-100)",
                "gray-200": "var(--gray-200)",
                "gray-300": "var(--gray-300)",
                "gray-400": "var(--gray-400)",
                "gray-500": "var(--gray-500)",
                "gray-600": "var(--gray-600)",
                "gray-700": "var(--gray-700)",
                "gray-800": "var(--gray-800)",
                "gray-900": "var(--gray-900)",
                "gray-950": "var(--gray-950)",
            },
        },
    },
    plugins: [require("tailwindcss-animate")],
};
export default config;
